#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

#networks:
#  basic:

networks:
  nmpnetwork:
    external:
      name: nmp-net

services:
  ca0.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: ca0
    container_name: ca0.nmplus.com
 
  ca1.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: ca1
    container_name: ca1.nmplus.com

  orderer.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer 
    container_name: orderer.nmplus.com

  peer0.org1.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: peer

    container_name: peer0.org1.nmplus.com
    image: hyperledger/fabric-peer${DOCKER_IMG_TAG}
    dns_search: .
    environment:
    - CORE_PEER_ID=peer0.org1.nmplus.com
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_ADDRESS=peer0.org1.nmplus.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer

    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.nmplus.com:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.nmplus.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.nmplus.com:7051

    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org1.nmplus.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # command: peer node start
    command: peer node start --peer-chaincodedev=true
    ports:
    - 7051:7051
    - 7053:7053
    volumes:
    - ../crypto-artifacts/peerOrganizations/org1.nmplus.com/peers/peer0.org1.nmplus.com/msp:/etc/hyperledger/msp/peer
    # - ../crypto-artifacts/peerOrganizations/org1.nmplus.com/users:/etc/hyperledger/msp/users
    # - peer0.org1.nmplus.com:/var/hyperledger/production
    depends_on:
    - orderer.nmplus.com
    - couchdb.org1.nmplus.com
    - couchdb.org2.nmplus.com
    networks:
    - nmpnetwork

  peer1.org1.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: peer

    container_name: peer1.org1.nmplus.com
    image: hyperledger/fabric-peer${DOCKER_IMG_TAG}
    dns_search: .
    environment:
    - CORE_PEER_ID=peer1.org1.nmplus.com
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_ADDRESS=peer1.org1.nmplus.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer

    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.nmplus.com:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer1.org1.nmplus.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.nmplus.com:7051

    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org1.nmplus.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # command: peer node start
    command: peer node start --peer-chaincodedev=true
    ports:
    - 7055:7051
    - 7056:7053
    volumes:
    - ../crypto-artifacts/peerOrganizations/org1.nmplus.com/peers/peer1.org1.nmplus.com/msp:/etc/hyperledger/msp/peer
    # - ../crypto-artifacts/peerOrganizations/org1.nmplus.com/users:/etc/hyperledger/msp/users
    # - peer0.org1.nmplus.com:/var/hyperledger/production
    depends_on:
    - orderer.nmplus.com
    - couchdb.org1.nmplus.com
    - couchdb.org2.nmplus.com
    networks:
    - nmpnetwork

  couchdb.org1.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: couchdb
    container_name: couchdb.org1.nmplus.com
    dns_search: .
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      DB_URL: http://couchdb.org1.nmplus.com:5984/member_db
    ports:
    - 5984:5984
    networks:
    - nmpnetwork

  peer0.org2.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: peer

    container_name: peer0.org2.nmplus.com
    image: hyperledger/fabric-peer${DOCKER_IMG_TAG}
    dns_search: .
    environment:
    - CORE_PEER_ID=peer0.org2.nmplus.com
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_ADDRESS=peer0.org2.nmplus.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer

    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.nmplus.com:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer0.org2.nmplus.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.nmplus.com:7051

    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org2.nmplus.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # command: peer node start
    command: peer node start --peer-chaincodedev=true
    ports:
    - 8051:7051
    - 8053:7053
    volumes:
    - ../crypto-artifacts/peerOrganizations/org2.nmplus.com/peers/peer0.org2.nmplus.com/msp:/etc/hyperledger/msp/peer
    # - ../crypto-artifacts/peerOrganizations/org2.nmplus.com/users:/etc/hyperledger/msp/users
    # - peer0.org2.nmplus.com:/var/hyperledger/production
    depends_on:
    - orderer.nmplus.com
    - couchdb.org1.nmplus.com
    - couchdb.org2.nmplus.com
    networks:
    - nmpnetwork

  peer1.org2.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: peer

    container_name: peer1.org2.nmplus.com
    image: hyperledger/fabric-peer${DOCKER_IMG_TAG}
    dns_search: .
    environment:
    - CORE_PEER_ID=peer1.org2.nmplus.com
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_ADDRESS=peer1.org2.nmplus.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer

    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.nmplus.com:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer1.org2.nmplus.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.nmplus.com:7051

    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org2.nmplus.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # command: peer node start
    command: peer node start --peer-chaincodedev=true
    ports:
    - 8055:7051
    - 8056:7053
    volumes:
    - ../crypto-artifacts/peerOrganizations/org2.nmplus.com/peers/peer1.org2.nmplus.com/msp:/etc/hyperledger/msp/peer
    # - ../crypto-artifacts/peerOrganizations/org2.nmplus.com/users:/etc/hyperledger/msp/users
    # - peer0.org2.nmplus.com:/var/hyperledger/production
    depends_on:
    - orderer.nmplus.com
    - couchdb.org1.nmplus.com
    - couchdb.org2.nmplus.com
    networks:
    - nmpnetwork

  couchdb.org2.nmplus.com:
    extends:
      file: docker-compose-base.yaml
      service: couchdb
    container_name: couchdb.org2.nmplus.com
    dns_search: .
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      #DB_URL: http://localhost:5984/member_db
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      DB_URL: http://couchdb.org1.nmplus.com:5984/member_db
    ports:
    - 5985:5984
    networks:
    - nmpnetwork

  org1-cli:
    container_name: org1-cli
    image: hyperledger/fabric-tools${DOCKER_IMG_TAG}
    tty: true
    environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=debug
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=peer0.org1.nmplus.com:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.nmplus.com/users/Admin@org1.nmplus.com/msp
    - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
    - /var/run/:/host/var/run/
    - ../cli:/opt/gopath/src/github.com/hyperledger/fabric/peer/cli
    - ../channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    - ../../chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/nmplus/chaincode/go
    - ../crypto-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
    - nmpnetwork
    depends_on:
    - orderer.nmplus.com
    - peer0.org1.nmplus.com
    - peer0.org2.nmplus.com
    - couchdb.org1.nmplus.com
    - couchdb.org2.nmplus.com

  org2-cli:
    container_name: org2-cli
    image: hyperledger/fabric-tools${DOCKER_IMG_TAG}
    tty: true
    environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=debug
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=peer0.org2.nmplus.com:7051
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.nmplus.com/users/Admin@org2.nmplus.com/msp
    - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
    - /var/run/:/host/var/run/
    - ../cli:/opt/gopath/src/github.com/hyperledger/fabric/peer/cli
    - ../channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    - ../../chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/nmplus/chaincode/go
    - ../crypto-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
    - nmpnetwork
    depends_on:
    - orderer.nmplus.com
    - peer0.org1.nmplus.com
    - peer0.org2.nmplus.com
    - couchdb.org1.nmplus.com
    - couchdb.org2.nmplus.com
