
---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-artifacts/ordererOrganizations/nmplus.com/msp
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-artifacts/peerOrganizations/org1.nmplus.com/msp
#        AnchorPeers:
#            - Host: peer0.org1.nmplus.com
#              Port: 7051
    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-artifacts/peerOrganizations/org2.nmplus.com/msp
#        AnchorPeers:
#            - Host: peer0.org2.nmplus.com
#              Port: 7052

Application: &ApplicationDefaults
    Organizations:

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        # - 127.0.0.1:7050
        - orderer.nmplus.com:7050
    BatchTimeout: 30s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Kafka:
        Brokers:
            - kafka0:9092
            # - kafka1:9092
            # - kafka2:9092

    Organizations:

Profiles:
    OneOrgOrdererGenesis: 
        Orderer: 
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium: 
                Organizations: 
                    - *Org1
                    - *Org2
    OneOrgChannel:
        Consortium: SampleConsortium
        Application: 
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2

